# Generated by Django 3.1.1 on 2020-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_auto_20201016_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
