# Generated by Django 3.1.1 on 2020-11-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_auto_20201126_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
